In [34]:
import zipfile
import os
import pandas as pd
import io

---

### OK DATA 
---

In [47]:
def txt_to_csv(input_file_name, output_file_name, delimiter='\t', header=True):
    # Get the current working directory
    cwd = os.getcwd()

    # Create full file paths
    input_file_path = os.path.join(cwd, input_file_name)
    output_file_path = os.path.join(cwd, output_file_name)

    # Read the text file
    header_row = 0 if header else None
    df = pd.read_csv(input_file_path, delimiter=delimiter, header=header_row)

    # Save the dataframe to a CSV file
    df.to_csv(output_file_path, index=False)

    # Ensure the CSV file has been created before deleting the TXT file
    if os.path.exists(output_file_path):
        os.remove(input_file_path)
    else:
        print("Error in converting to CSV, TXT file not deleted.")

In [48]:
txt_to_csv('OK_Data.txt', 'OK_Data.csv')

C:\Users\iandr\AppData\Local\Temp\ipykernel_9352\3148540490.py:11: DtypeWarning: Columns (14,21,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(input_file_path, delimiter=delimiter, header=header_row)

In [49]:
def zip_top_species_csv(input_csv, output_zip):
    # Read the CSV into a DataFrame
    df = pd.read_csv(input_csv)

    # Identify the top 10 common names
    df['OBSERVATION COUNT'] = pd.to_numeric(df['OBSERVATION COUNT'].str.replace('X', '0').str.strip())
    top_species = df.groupby('COMMON NAME')['OBSERVATION COUNT'].sum().nlargest(20).index

    # Filter the DataFrame
    filtered_df = df[df['COMMON NAME'].isin(top_species)]

    # Create a buffer to write the filtered DataFrame to
    buffer = io.StringIO()
    filtered_df.to_csv(buffer, index=False)
    buffer.seek(0)  # Rewind the buffer

    # Zip the buffered CSV
    with zipfile.ZipFile(output_zip, 'w', zipfile.ZIP_DEFLATED) as zipf:
        zipf.writestr(os.path.basename(input_csv), buffer.getvalue())

    # Check if the zip file has been created and is not empty before deleting the original CSV
    if os.path.exists(output_zip) and os.path.getsize(output_zip) > 0:
        os.remove(input_csv)
    else:
        print("Error in zipping process, original CSV file not deleted.")

In [50]:
zip_top_species_csv('OK_Data.csv', 'OK_Data.zip')

C:\Users\iandr\AppData\Local\Temp\ipykernel_9352\3329338149.py:3: DtypeWarning: Columns (14,21,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(input_csv)

In [51]:
def unzip_and_read_csv(input_zip):
    with zipfile.ZipFile(input_zip, 'r') as zipf:
        # Assuming there's only one file in the zip
        csv_file_name = zipf.namelist()[0]
        with zipf.open(csv_file_name) as csv_file:
            return pd.read_csv(csv_file)

In [52]:
df = unzip_and_read_csv('OK_Data.zip')
df

,GLOBAL UNIQUE IDENTIFIER,LAST EDITED DATE,TAXONOMIC ORDER,CATEGORY,TAXON CONCEPT ID,COMMON NAME,SCIENTIFIC NAME,SUBSPECIES COMMON NAME,SUBSPECIES SCIENTIFIC NAME,EXOTIC CODE,...,NUMBER OBSERVERS,ALL SPECIES REPORTED,GROUP IDENTIFIER,HAS MEDIA,APPROVED,REVIEWED,REASON,TRIP COMMENTS,SPECIES COMMENTS,Unnamed: 49
0,URN:CornellLabOfOrnithology:EBIRD:OBS1330103582,2022-01-29 23:08:22.754555,21168,species,avibase-69544B59,American Crow,Corvus brachyrhynchos,NaN,NaN,NaN,...,1.0,1,NaN,0,1,0,NaN,NaN,NaN,NaN
1,URN:CornellLabOfOrnithology:EBIRD:OBS1327041665,2022-01-25 15:13:52.983578,21168,species,avibase-69544B59,American Crow,Corvus brachyrhynchos,NaN,NaN,NaN,...,1.0,1,NaN,0,1,0,NaN,32Â° F; sky 2,NaN,NaN
2,URN:CornellLabOfOrnithology:EBIRD:OBS1330086699,2022-01-29 23:11:05.004569,21168,species,avibase-69544B59,American Crow,Corvus brachyrhynchos,NaN,NaN,NaN,...,2.0,1,NaN,0,1,0,NaN,NaN,NaN,NaN
3,URN:CornellLabOfOrnithology:EBIRD:OBS1308805008,2022-01-03 00:35:37.00912,21168,species,avibase-69544B59,American Crow,Corvus brachyrhynchos,NaN,NaN,NaN,...,1.0,1,NaN,0,1,0,NaN,NaN,NaN,NaN
4,URN:CornellLabOfOrnithology:EBIRD:OBS1309104884,2022-01-02 17:33:18.64746,21168,species,avibase-69544B59,American Crow,Corvus brachyrhynchos,NaN,NaN,NaN,...,1.0,1,NaN,0,1,0,NaN,"Eagle roost, auto loop, and Casey tower",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
228525,URN:CornellLabOfOrnithology:EBIRD:OBS1842039225,2023-10-07 22:47:56.19734,33967,species,avibase-4E74AE22,Northern Cardinal,Cardinalis cardinalis,NaN,NaN,NaN,...,2.0,1,NaN,0,1,0,NaN,did not see the long-tailed jaeger,NaN,NaN
228526,URN:CornellLabOfOrnithology:EBIRD:OBS1848228778,2023-10-16 00:32:16.23152,6479,species,avibase-23863F65,Ring-billed Gull,Larus delawarensis,NaN,NaN,NaN,...,1.0,1,NaN,1,1,0,NaN,NaN,Featuring the successful rescue by kayak of on...,NaN
228527,URN:CornellLabOfOrnithology:EBIRD:OBS1842039224,2023-10-07 22:47:56.19734,6479,species,avibase-23863F65,Ring-billed Gull,Larus delawarensis,NaN,NaN,NaN,...,2.0,1,NaN,0,1,0,NaN,did not see the long-tailed jaeger,NaN,NaN
228528,URN:CornellLabOfOrnithology:EBIRD:OBS1855034037,2023-10-19 13:11:59.30086,6479,species,avibase-23863F65,Ring-billed Gull,Larus delawarensis,NaN,NaN,NaN,...,2.0,1,NaN,0,1,0,NaN,NaN,NaN,NaN
228529,URN:CornellLabOfOrnithology:EBIRD:OBS1840034747,2023-10-26 00:57:00.528478,6479,species,avibase-23863F65,Ring-billed Gull,Larus delawarensis,NaN,NaN,NaN,...,1.0,1,NaN,1,1,0,NaN,Ended the checklist early to get the word out ...,NaN,NaN

---

### AK DATA
---

In [53]:
txt_to_csv('AK_Data.txt', 'AK_Data.csv')

C:\Users\iandr\AppData\Local\Temp\ipykernel_9352\3148540490.py:11: DtypeWarning: Columns (21,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(input_file_path, delimiter=delimiter, header=header_row)

In [54]:
zip_top_species_csv('AK_Data.csv', 'AK_Data.zip')

C:\Users\iandr\AppData\Local\Temp\ipykernel_9352\3329338149.py:3: DtypeWarning: Columns (21,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(input_csv)

In [55]:
df = unzip_and_read_csv('AK_Data.zip')
df

,GLOBAL UNIQUE IDENTIFIER,LAST EDITED DATE,TAXONOMIC ORDER,CATEGORY,TAXON CONCEPT ID,COMMON NAME,SCIENTIFIC NAME,SUBSPECIES COMMON NAME,SUBSPECIES SCIENTIFIC NAME,EXOTIC CODE,...,NUMBER OBSERVERS,ALL SPECIES REPORTED,GROUP IDENTIFIER,HAS MEDIA,APPROVED,REVIEWED,REASON,TRIP COMMENTS,SPECIES COMMENTS,Unnamed: 49
0,URN:CornellLabOfOrnithology:EBIRD:OBS1311142624,2022-01-04 22:58:04.20696,21168,species,avibase-69544B59,American Crow,Corvus brachyrhynchos,NaN,NaN,NaN,...,2.0,0,G7664408,0,1,0,NaN,White River CBC species. Section 5. List done ...,NaN,NaN
1,URN:CornellLabOfOrnithology:EBIRD:OBS1310524086,2022-01-04 22:00:44.395734,21168,species,avibase-69544B59,American Crow,Corvus brachyrhynchos,NaN,NaN,NaN,...,1.0,1,NaN,0,1,0,NaN,NaN,NaN,NaN
2,URN:CornellLabOfOrnithology:EBIRD:OBS1308030546,2022-01-01 18:02:38.794608,21168,species,avibase-69544B59,American Crow,Corvus brachyrhynchos,NaN,NaN,NaN,...,1.0,1,NaN,0,1,0,NaN,NaN,NaN,NaN
3,URN:CornellLabOfOrnithology:EBIRD:OBS1310540351,2022-01-04 09:19:43.242862,21168,species,avibase-69544B59,American Crow,Corvus brachyrhynchos,NaN,NaN,NaN,...,1.0,1,NaN,0,1,0,NaN,NaN,NaN,NaN
4,URN:CornellLabOfOrnithology:EBIRD:OBS1311153239,2022-01-04 22:58:04.20696,21168,species,avibase-69544B59,American Crow,Corvus brachyrhynchos,NaN,NaN,NaN,...,2.0,0,G7664408,0,1,0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211404,URN:CornellLabOfOrnithology:EBIRD:OBS1857672965,2023-10-22 19:16:33.486151,6479,species,avibase-23863F65,Ring-billed Gull,Larus delawarensis,NaN,NaN,NaN,...,2.0,1,NaN,0,1,0,NaN,NaN,NaN,NaN
211405,URN:CornellLabOfOrnithology:EBIRD:OBS1859718360,2023-10-25 15:28:40.240338,6479,species,avibase-23863F65,Ring-billed Gull,Larus delawarensis,NaN,NaN,NaN,...,2.0,1,NaN,0,1,0,NaN,NaN,NaN,NaN
211406,URN:CornellLabOfOrnithology:EBIRD:OBS1844359302,2023-10-07 12:19:31.586694,6479,species,avibase-23863F65,Ring-billed Gull,Larus delawarensis,NaN,NaN,NaN,...,1.0,1,NaN,0,1,0,NaN,NaN,NaN,NaN
211407,URN:CornellLabOfOrnithology:EBIRD:OBS1844347025,2023-10-10 17:23:22.455463,6479,species,avibase-23863F65,Ring-billed Gull,Larus delawarensis,NaN,NaN,NaN,...,1.0,1,NaN,0,1,0,NaN,NaN,NaN,NaN
211408,URN:CornellLabOfOrnithology:EBIRD:OBS1847824564,2023-10-11 14:52:53.805437,6479,species,avibase-23863F65,Ring-billed Gull,Larus delawarensis,NaN,NaN,NaN,...,1.0,1,NaN,0,1,0,NaN,NaN,NaN,NaN

In [56]:
import pandas as pd
import requests
import zipfile
import io

def read_csv_from_zip_url(url):
    response = requests.get(url)
    with zipfile.ZipFile(io.BytesIO(response.content)) as zipf:
        # Assuming there's only one file in the zip
        csv_file_name = zipf.namelist()[0]
        with zipf.open(csv_file_name) as csv_file:
            return pd.read_csv(csv_file)

# Example usage with the direct URL to the raw zip file data
url = 'https://github.com/Iandrewburg/DV2_Assignment/blob/main/OK_Data.zip?raw=true'  # Replace with the direct link
df = read_csv_from_zip_url(url)
df

,GLOBAL UNIQUE IDENTIFIER,LAST EDITED DATE,TAXONOMIC ORDER,CATEGORY,TAXON CONCEPT ID,COMMON NAME,SCIENTIFIC NAME,SUBSPECIES COMMON NAME,SUBSPECIES SCIENTIFIC NAME,EXOTIC CODE,...,NUMBER OBSERVERS,ALL SPECIES REPORTED,GROUP IDENTIFIER,HAS MEDIA,APPROVED,REVIEWED,REASON,TRIP COMMENTS,SPECIES COMMENTS,Unnamed: 49
0,URN:CornellLabOfOrnithology:EBIRD:OBS1330103582,2022-01-29 23:08:22.754555,21168,species,avibase-69544B59,American Crow,Corvus brachyrhynchos,NaN,NaN,NaN,...,1.0,1,NaN,0,1,0,NaN,NaN,NaN,NaN
1,URN:CornellLabOfOrnithology:EBIRD:OBS1327041665,2022-01-25 15:13:52.983578,21168,species,avibase-69544B59,American Crow,Corvus brachyrhynchos,NaN,NaN,NaN,...,1.0,1,NaN,0,1,0,NaN,32Â° F; sky 2,NaN,NaN
2,URN:CornellLabOfOrnithology:EBIRD:OBS1330086699,2022-01-29 23:11:05.004569,21168,species,avibase-69544B59,American Crow,Corvus brachyrhynchos,NaN,NaN,NaN,...,2.0,1,NaN,0,1,0,NaN,NaN,NaN,NaN
3,URN:CornellLabOfOrnithology:EBIRD:OBS1308805008,2022-01-03 00:35:37.00912,21168,species,avibase-69544B59,American Crow,Corvus brachyrhynchos,NaN,NaN,NaN,...,1.0,1,NaN,0,1,0,NaN,NaN,NaN,NaN
4,URN:CornellLabOfOrnithology:EBIRD:OBS1309104884,2022-01-02 17:33:18.64746,21168,species,avibase-69544B59,American Crow,Corvus brachyrhynchos,NaN,NaN,NaN,...,1.0,1,NaN,0,1,0,NaN,"Eagle roost, auto loop, and Casey tower",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
228525,URN:CornellLabOfOrnithology:EBIRD:OBS1842039225,2023-10-07 22:47:56.19734,33967,species,avibase-4E74AE22,Northern Cardinal,Cardinalis cardinalis,NaN,NaN,NaN,...,2.0,1,NaN,0,1,0,NaN,did not see the long-tailed jaeger,NaN,NaN
228526,URN:CornellLabOfOrnithology:EBIRD:OBS1848228778,2023-10-16 00:32:16.23152,6479,species,avibase-23863F65,Ring-billed Gull,Larus delawarensis,NaN,NaN,NaN,...,1.0,1,NaN,1,1,0,NaN,NaN,Featuring the successful rescue by kayak of on...,NaN
228527,URN:CornellLabOfOrnithology:EBIRD:OBS1842039224,2023-10-07 22:47:56.19734,6479,species,avibase-23863F65,Ring-billed Gull,Larus delawarensis,NaN,NaN,NaN,...,2.0,1,NaN,0,1,0,NaN,did not see the long-tailed jaeger,NaN,NaN
228528,URN:CornellLabOfOrnithology:EBIRD:OBS1855034037,2023-10-19 13:11:59.30086,6479,species,avibase-23863F65,Ring-billed Gull,Larus delawarensis,NaN,NaN,NaN,...,2.0,1,NaN,0,1,0,NaN,NaN,NaN,NaN
228529,URN:CornellLabOfOrnithology:EBIRD:OBS1840034747,2023-10-26 00:57:00.528478,6479,species,avibase-23863F65,Ring-billed Gull,Larus delawarensis,NaN,NaN,NaN,...,1.0,1,NaN,1,1,0,NaN,Ended the checklist early to get the word out ...,NaN,NaN