In [3]:
import zipfile
import os
import pandas as pd
import io

---

### OK DATA 
---

In [4]:
def txt_to_csv(input_file_name, output_file_name, delimiter='\t', header=True):
    # Get the current working directory
    cwd = os.getcwd()

    # Create full file paths
    input_file_path = os.path.join(cwd, input_file_name)
    output_file_path = os.path.join(cwd, output_file_name)

    # Read the text file
    header_row = 0 if header else None
    df = pd.read_csv(input_file_path, delimiter=delimiter, header=header_row)

    # Save the dataframe to a CSV file
    df.to_csv(output_file_path, index=False)

    # Ensure the CSV file has been created before deleting the TXT file
    if os.path.exists(output_file_path):
        os.remove(input_file_path)
    else:
        print("Error in converting to CSV, TXT file not deleted.")

In [5]:
txt_to_csv('OK_Data.txt', 'OK_Data.csv')

C:\Users\iandr\AppData\Local\Temp\ipykernel_25896\3148540490.py:11: DtypeWarning: Columns (14,21,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(input_file_path, delimiter=delimiter, header=header_row)

In [6]:
def zip_csv(input_csv, output_zip):
    # Read the CSV into a DataFrame
    df = pd.read_csv(input_csv)

    # No need to identify and filter by top species; we skip that step

    # Create a buffer to write the DataFrame to
    buffer = io.StringIO()
    df.to_csv(buffer, index=False)
    buffer.seek(0)  # Rewind the buffer

    # Zip the buffered CSV
    with zipfile.ZipFile(output_zip, 'w', zipfile.ZIP_DEFLATED) as zipf:
        zipf.writestr(os.path.basename(input_csv), buffer.getvalue())

    # Check if the zip file has been created and is not empty before deleting the original CSV
    if os.path.exists(output_zip) and os.path.getsize(output_zip) > 0:
        os.remove(input_csv)
    else:
        print("Error in zipping process, original CSV file not deleted.")

In [7]:
zip_csv('OK_Data.csv', 'OK_Data.zip')

C:\Users\iandr\AppData\Local\Temp\ipykernel_25896\24313071.py:8: DtypeWarning: Columns (14,21,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(input_csv)

In [8]:
def unzip_and_read_csv(input_zip):
    with zipfile.ZipFile(input_zip, 'r') as zipf:
        # Assuming there's only one file in the zip
        csv_file_name = zipf.namelist()[0]
        with zipf.open(csv_file_name) as csv_file:
            return pd.read_csv(csv_file)

In [9]:
df = unzip_and_read_csv('OK_Data.zip')
df

C:\Users\iandr\AppData\Local\Temp\ipykernel_25896\3041235366.py:6: DtypeWarning: Columns (14,21,23) have mixed types. Specify dtype option on import or set low_memory=False.
  return pd.read_csv(csv_file)

,GLOBAL UNIQUE IDENTIFIER,LAST EDITED DATE,TAXONOMIC ORDER,CATEGORY,TAXON CONCEPT ID,COMMON NAME,SCIENTIFIC NAME,SUBSPECIES COMMON NAME,SUBSPECIES SCIENTIFIC NAME,EXOTIC CODE,...,NUMBER OBSERVERS,ALL SPECIES REPORTED,GROUP IDENTIFIER,HAS MEDIA,APPROVED,REVIEWED,REASON,TRIP COMMENTS,SPECIES COMMENTS,Unnamed: 49
0,URN:CornellLabOfOrnithology:EBIRD:OBS1308805025,2022-01-03 00:35:37.00912,5751,species,avibase-8EB0C1FA,American Avocet,Recurvirostra americana,NaN,NaN,NaN,...,1.0,1,NaN,0,1,1,NaN,NaN,Below spillway with greater yellowlegs,NaN
1,URN:CornellLabOfOrnithology:EBIRD:OBS1330103582,2022-01-29 23:08:22.754555,21168,species,avibase-69544B59,American Crow,Corvus brachyrhynchos,NaN,NaN,NaN,...,1.0,1,NaN,0,1,0,NaN,NaN,NaN,NaN
2,URN:CornellLabOfOrnithology:EBIRD:OBS1327041665,2022-01-25 15:13:52.983578,21168,species,avibase-69544B59,American Crow,Corvus brachyrhynchos,NaN,NaN,NaN,...,1.0,1,NaN,0,1,0,NaN,32Â° F; sky 2,NaN,NaN
3,URN:CornellLabOfOrnithology:EBIRD:OBS1330086699,2022-01-29 23:11:05.004569,21168,species,avibase-69544B59,American Crow,Corvus brachyrhynchos,NaN,NaN,NaN,...,2.0,1,NaN,0,1,0,NaN,NaN,NaN,NaN
4,URN:CornellLabOfOrnithology:EBIRD:OBS1308805008,2022-01-03 00:35:37.00912,21168,species,avibase-69544B59,American Crow,Corvus brachyrhynchos,NaN,NaN,NaN,...,1.0,1,NaN,0,1,0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1001663,URN:CornellLabOfOrnithology:EBIRD:OBS1845618187,2023-10-08 18:29:45.359642,7624,species,avibase-36B3872D,Turkey Vulture,Cathartes aura,NaN,NaN,NaN,...,1.0,1,NaN,1,1,0,NaN,NaN,NaN,NaN
1001664,URN:CornellLabOfOrnithology:EBIRD:OBS1848228777,2023-10-16 00:32:16.23152,26436,species,avibase-19CCBBD2,White-breasted Nuthatch,Sitta carolinensis,NaN,NaN,NaN,...,1.0,1,NaN,0,1,0,NaN,NaN,NaN,NaN
1001665,URN:CornellLabOfOrnithology:EBIRD:OBS1845618189,2023-10-08 18:29:45.359642,433,species,avibase-27B2749A,Wood Duck,Aix sponsa,NaN,NaN,NaN,...,1.0,1,NaN,1,1,0,NaN,NaN,NaN,NaN
1001666,URN:CornellLabOfOrnithology:EBIRD:OBS1848207162,2023-10-16 00:32:16.23152,33622,species,avibase-BC5A9498,Yellow-rumped Warbler,Setophaga coronata,NaN,NaN,NaN,...,1.0,1,NaN,1,1,0,NaN,NaN,NaN,NaN
1001667,URN:CornellLabOfOrnithology:EBIRD:OBS1845584337,2023-10-10 00:28:47.000714,33622,species,avibase-BC5A9498,Yellow-rumped Warbler,Setophaga coronata,NaN,NaN,NaN,...,1.0,1,NaN,0,1,0,NaN,NaN,NaN,NaN

---

### AK DATA
---

In [10]:
txt_to_csv('AK_Data.txt', 'AK_Data.csv')

C:\Users\iandr\AppData\Local\Temp\ipykernel_25896\3148540490.py:11: DtypeWarning: Columns (21,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(input_file_path, delimiter=delimiter, header=header_row)

In [12]:
zip_csv('AK_Data.csv', 'AK_Data.zip')

C:\Users\iandr\AppData\Local\Temp\ipykernel_25896\24313071.py:8: DtypeWarning: Columns (21,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(input_csv)

In [13]:
df = unzip_and_read_csv('AK_Data.zip')
df

C:\Users\iandr\AppData\Local\Temp\ipykernel_25896\3041235366.py:6: DtypeWarning: Columns (21,23) have mixed types. Specify dtype option on import or set low_memory=False.
  return pd.read_csv(csv_file)

,GLOBAL UNIQUE IDENTIFIER,LAST EDITED DATE,TAXONOMIC ORDER,CATEGORY,TAXON CONCEPT ID,COMMON NAME,SCIENTIFIC NAME,SUBSPECIES COMMON NAME,SUBSPECIES SCIENTIFIC NAME,EXOTIC CODE,...,NUMBER OBSERVERS,ALL SPECIES REPORTED,GROUP IDENTIFIER,HAS MEDIA,APPROVED,REVIEWED,REASON,TRIP COMMENTS,SPECIES COMMENTS,Unnamed: 49
0,URN:CornellLabOfOrnithology:EBIRD:OBS1311142624,2022-01-04 22:58:04.20696,21168,species,avibase-69544B59,American Crow,Corvus brachyrhynchos,NaN,NaN,NaN,...,2.0,0,G7664408,0,1,0,NaN,White River CBC species. Section 5. List done ...,NaN,NaN
1,URN:CornellLabOfOrnithology:EBIRD:OBS1310524086,2022-01-04 22:00:44.395734,21168,species,avibase-69544B59,American Crow,Corvus brachyrhynchos,NaN,NaN,NaN,...,1.0,1,NaN,0,1,0,NaN,NaN,NaN,NaN
2,URN:CornellLabOfOrnithology:EBIRD:OBS1308030546,2022-01-01 18:02:38.794608,21168,species,avibase-69544B59,American Crow,Corvus brachyrhynchos,NaN,NaN,NaN,...,1.0,1,NaN,0,1,0,NaN,NaN,NaN,NaN
3,URN:CornellLabOfOrnithology:EBIRD:OBS1310540351,2022-01-04 09:19:43.242862,21168,species,avibase-69544B59,American Crow,Corvus brachyrhynchos,NaN,NaN,NaN,...,1.0,1,NaN,0,1,0,NaN,NaN,NaN,NaN
4,URN:CornellLabOfOrnithology:EBIRD:OBS1311153239,2022-01-04 22:58:04.20696,21168,species,avibase-69544B59,American Crow,Corvus brachyrhynchos,NaN,NaN,NaN,...,2.0,0,G7664408,0,1,0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1141336,URN:CornellLabOfOrnithology:EBIRD:OBS1839738362,2023-10-01 10:25:00.414318,32672,species,avibase-39BD9FF2,White-throated Sparrow,Zonotrichia albicollis,NaN,NaN,NaN,...,1.0,1,NaN,0,1,0,NaN,NaN,NaN,NaN
1141337,URN:CornellLabOfOrnithology:EBIRD:OBS1839738341,2023-10-01 10:25:00.414318,1222,species,avibase-9C5ED06A,Wild Turkey,Meleagris gallopavo,NaN,NaN,NaN,...,1.0,1,NaN,0,1,0,NaN,NaN,NaN,NaN
1141338,URN:CornellLabOfOrnithology:EBIRD:OBS1844359299,2023-10-07 12:19:31.586694,433,species,avibase-27B2749A,Wood Duck,Aix sponsa,NaN,NaN,NaN,...,1.0,1,NaN,0,1,0,NaN,NaN,NaN,NaN
1141339,URN:CornellLabOfOrnithology:EBIRD:OBS1849349241,2023-10-16 09:04:20.873962,27192,spuh,avibase-D81CDBB1,wren sp.,Troglodytidae sp.,NaN,NaN,NaN,...,2.0,1,NaN,0,1,1,NaN,NaN,At least this many. I think most were Sedge Wr...,NaN
1141340,URN:CornellLabOfOrnithology:EBIRD:OBS1859718380,2023-10-25 15:28:40.240338,33622,species,avibase-BC5A9498,Yellow-rumped Warbler,Setophaga coronata,NaN,NaN,NaN,...,2.0,1,NaN,0,1,0,NaN,NaN,NaN,NaN

In [14]:
import pandas as pd
import requests
import zipfile
import io

def read_csv_from_zip_url(url):
    response = requests.get(url)
    with zipfile.ZipFile(io.BytesIO(response.content)) as zipf:
        # Assuming there's only one file in the zip
        csv_file_name = zipf.namelist()[0]
        with zipf.open(csv_file_name) as csv_file:
            return pd.read_csv(csv_file)

# Example usage with the direct URL to the raw zip file data
url = 'https://github.com/Iandrewburg/DV2_Assignment/blob/main/OK_Data.zip?raw=true'  # Replace with the direct link
df = read_csv_from_zip_url(url)
df

C:\Users\iandr\AppData\Local\Temp\ipykernel_25896\1307930721.py:12: DtypeWarning: Columns (14,21,23) have mixed types. Specify dtype option on import or set low_memory=False.
  return pd.read_csv(csv_file)

,GLOBAL UNIQUE IDENTIFIER,LAST EDITED DATE,TAXONOMIC ORDER,CATEGORY,TAXON CONCEPT ID,COMMON NAME,SCIENTIFIC NAME,SUBSPECIES COMMON NAME,SUBSPECIES SCIENTIFIC NAME,EXOTIC CODE,...,NUMBER OBSERVERS,ALL SPECIES REPORTED,GROUP IDENTIFIER,HAS MEDIA,APPROVED,REVIEWED,REASON,TRIP COMMENTS,SPECIES COMMENTS,Unnamed: 49
0,URN:CornellLabOfOrnithology:EBIRD:OBS1308805025,2022-01-03 00:35:37.00912,5751,species,avibase-8EB0C1FA,American Avocet,Recurvirostra americana,NaN,NaN,NaN,...,1.0,1,NaN,0,1,1,NaN,NaN,Below spillway with greater yellowlegs,NaN
1,URN:CornellLabOfOrnithology:EBIRD:OBS1330103582,2022-01-29 23:08:22.754555,21168,species,avibase-69544B59,American Crow,Corvus brachyrhynchos,NaN,NaN,NaN,...,1.0,1,NaN,0,1,0,NaN,NaN,NaN,NaN
2,URN:CornellLabOfOrnithology:EBIRD:OBS1327041665,2022-01-25 15:13:52.983578,21168,species,avibase-69544B59,American Crow,Corvus brachyrhynchos,NaN,NaN,NaN,...,1.0,1,NaN,0,1,0,NaN,32Â° F; sky 2,NaN,NaN
3,URN:CornellLabOfOrnithology:EBIRD:OBS1330086699,2022-01-29 23:11:05.004569,21168,species,avibase-69544B59,American Crow,Corvus brachyrhynchos,NaN,NaN,NaN,...,2.0,1,NaN,0,1,0,NaN,NaN,NaN,NaN
4,URN:CornellLabOfOrnithology:EBIRD:OBS1308805008,2022-01-03 00:35:37.00912,21168,species,avibase-69544B59,American Crow,Corvus brachyrhynchos,NaN,NaN,NaN,...,1.0,1,NaN,0,1,0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1001663,URN:CornellLabOfOrnithology:EBIRD:OBS1845618187,2023-10-08 18:29:45.359642,7624,species,avibase-36B3872D,Turkey Vulture,Cathartes aura,NaN,NaN,NaN,...,1.0,1,NaN,1,1,0,NaN,NaN,NaN,NaN
1001664,URN:CornellLabOfOrnithology:EBIRD:OBS1848228777,2023-10-16 00:32:16.23152,26436,species,avibase-19CCBBD2,White-breasted Nuthatch,Sitta carolinensis,NaN,NaN,NaN,...,1.0,1,NaN,0,1,0,NaN,NaN,NaN,NaN
1001665,URN:CornellLabOfOrnithology:EBIRD:OBS1845618189,2023-10-08 18:29:45.359642,433,species,avibase-27B2749A,Wood Duck,Aix sponsa,NaN,NaN,NaN,...,1.0,1,NaN,1,1,0,NaN,NaN,NaN,NaN
1001666,URN:CornellLabOfOrnithology:EBIRD:OBS1848207162,2023-10-16 00:32:16.23152,33622,species,avibase-BC5A9498,Yellow-rumped Warbler,Setophaga coronata,NaN,NaN,NaN,...,1.0,1,NaN,1,1,0,NaN,NaN,NaN,NaN
1001667,URN:CornellLabOfOrnithology:EBIRD:OBS1845584337,2023-10-10 00:28:47.000714,33622,species,avibase-BC5A9498,Yellow-rumped Warbler,Setophaga coronata,NaN,NaN,NaN,...,1.0,1,NaN,0,1,0,NaN,NaN,NaN,NaN